# Generated by Django 2.2.5 on 2021-03-12 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_start_1', models.TimeField()),
                ('mon_end_1', models.TimeField()),
                ('mon_start_2', models.TimeField()),
                ('mon_end_2', models.TimeField()),
                ('tue_start_1', models.TimeField()),
                ('tue_end_1', models.TimeField()),
                ('tue_start_2', models.TimeField()),
                ('tue_end_2', models.TimeField()),
                ('wed_start_1', models.TimeField()),
                ('wed_end_1', models.TimeField()),
                ('wed_start_2', models.TimeField()),
                ('wed_end_2', models.TimeField()),
                ('thur_start_1', models.TimeField()),
                ('thur_end_1', models.TimeField()),
                ('thur_start_2', models.TimeField()),
                ('thur_end_2', models.TimeField()),
                ('fri_start_1', models.TimeField()),
                ('fri_end_1', models.TimeField()),
                ('fri_start_2', models.TimeField()),
                ('fri_end_2', models.TimeField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_start_1', models.TimeField()),
                ('mon_end_1', models.TimeField()),
                ('mon_start_2', models.TimeField()),
                ('mon_end_2', models.TimeField()),
                ('tue_start_1', models.TimeField()),
                ('tue_end_1', models.TimeField()),
                ('tue_start_2', models.TimeField()),
                ('tue_end_2', models.TimeField()),
                ('wed_start_1', models.TimeField()),
                ('wed_end_1', models.TimeField()),
                ('wed_start_2', models.TimeField()),
                ('wed_end_2', models.TimeField()),
                ('thur_start_1', models.TimeField()),
                ('thur_end_1', models.TimeField()),
                ('thur_start_2', models.TimeField()),
                ('thur_end_2', models.TimeField()),
                ('fri_start_1', models.TimeField()),
                ('fri_end_1', models.TimeField()),
                ('fri_start_2', models.TimeField()),
                ('fri_end_2', models.TimeField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('max_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
