# Generated by Django 2.2.5 on 2021-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0, max_length=8),
        ),
    ]
