# Generated by Django 2.2.5 on 2021-06-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
