# Generated by Django 2.2.5 on 2021-06-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_availability_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='update_date',
            new_name='approval_date',
        ),
    ]
