# Generated by Django 2.2.5 on 2022-11-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210616_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='thur_end_1',
            new_name='thu_end_1',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='thur_end_2',
            new_name='thu_end_2',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='thur_start_1',
            new_name='thu_start_1',
        ),
        migrations.RenameField(
            model_name='availability',
            old_name='thur_start_2',
            new_name='thu_start_2',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='thur_end_1',
            new_name='thu_end_1',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='thur_end_2',
            new_name='thu_end_2',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='thur_start_1',
            new_name='thu_start_1',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='thur_start_2',
            new_name='thu_start_2',
        ),
    ]
