# Generated by Django 2.2.5 on 2022-05-04 23:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210616_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='availabilities',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
