# Generated by Django 2.2.5 on 2022-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20221104_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='hours_check',
            field=models.BooleanField(default=False),
        ),
    ]
