# Generated by Django 2.2.5 on 2022-12-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedule_hours_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='hours_check',
        ),
    ]
