# Generated by Django 2.2.5 on 2023-02-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_schedule_hours_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('meeting_type', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.CharField(max_length=200)),
            ],
        ),
    ]
