# Generated by Django 2.2.5 on 2023-02-20 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_teammeetings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammeetings',
            old_name='start',
            new_name='fri_end_1',
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='fri_start_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='mon_end_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='mon_start_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='thu_end_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='thu_start_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='tue_end_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='tue_start_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='wed_end_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammeetings',
            name='wed_start_1',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
