# Generated by Django 2.2.5 on 2023-02-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20230220_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammeetings',
            old_name='fri_end_1',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='teammeetings',
            old_name='fri_start_1',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='mon_end_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='mon_start_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='thu_end_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='thu_start_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='tue_end_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='tue_start_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='wed_end_1',
        ),
        migrations.RemoveField(
            model_name='teammeetings',
            name='wed_start_1',
        ),
    ]
