# Generated by Django 2.2.5 on 2023-02-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20230220_2233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMeetings',
            new_name='TeamMeeting',
        ),
    ]
