# Generated by Django 2.2.5 on 2023-03-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_auto_20230227_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammeeting',
            name='day',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
