# Generated by Django 2.2.5 on 2023-03-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_teammeeting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
