# Generated by Django 2.2.5 on 2023-03-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_auto_20230301_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammeeting',
            old_name='day',
            new_name='days',
        ),
        migrations.AddField(
            model_name='teammeeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
