# Generated by Django 2.2.5 on 2023-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_auto_20230328_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
