# Generated by Django 2.2.5 on 2023-03-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0018_auto_20230329_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
