# Generated by Django 2.2.5 on 2023-03-29 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_auto_20230329_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
