# Generated by Django 2.2.5 on 2023-03-29 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0020_auto_20230329_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='days',
            field=models.CharField(max_length=25, validators=[django.core.validators.int_list_validator]),
        ),
    ]
