# Generated by Django 2.2.5 on 2023-03-29 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_auto_20230329_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammeeting',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
