# Generated by Django 2.2.5 on 2021-03-12 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_timeoff', models.DateField()),
                ('text_box', models.TextField(max_length=500)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], max_length=1, verbose_name='status')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('timeoff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timeoff.Timeoff')),
            ],
        ),
    ]
