# Generated by Django 2.2.5 on 2021-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0002_auto_20210416_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='type',
            field=models.CharField(default='sick leave', max_length=30),
            preserve_default=False,
        ),
    ]
