# Generated by Django 2.2.5 on 2021-04-26 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0003_timeoff_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoff',
            old_name='type',
            new_name='timeoff_type',
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
