# Generated by Django 2.2.5 on 2021-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0004_auto_20210426_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoff',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
