# Generated by Django 2.2.5 on 2023-03-15 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0005_auto_20210427_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeoff',
            old_name='from_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='description',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='submission_date',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='timeoff_type',
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='to_date',
        ),
        migrations.AddField(
            model_name='timeoff',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoff',
            name='end_date',
            field=models.DateField(default='1992-02-16'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeoff',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='request_type',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='status',
            field=models.CharField(max_length=8),
        ),
    ]
