# Generated by Django 2.2.5 on 2023-03-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0006_auto_20230315_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='end_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='timeoff',
            name='start_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
