# Generated by Django 2.2.5 on 2023-03-15 14:59

from django.db import migrations
import timeoff.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0008_auto_20230315_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='end_date',
            field=timeoff.models.EmptyStringToNoneField(blank=True, default='2000-01-01', null=True),
        ),
    ]
