# Generated by Django 2.2.5 on 2023-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeoff', '0009_auto_20230315_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoff',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0, max_length=8),
        ),
    ]
